### ISSUE TITLE
Add example for how to use this as remark plugin

### ISSUE THREAD

**Issue by kai687** [remcohaszing/unified-prettier#2]
Hi, I came across this from `remark-prettier`, which I read is considered deprecated.

With `remark-prettier`, I just have to add it to the list of plugins in the `.remarkconfig.js` file and I can use it with `remark-cli` to format Markdown files. 

If I try to do the same with `unified-prettier`, I get this error:

```
error  TypeError: Cannot `stringify` without `Compiler`
```

I'm obviously doing something wrong here...

Could you provide an example to the README, how to configure `remark` to replace `remark-prettier` with this plugin? 

My remark config:

```js
// .remarkrc.mjs
export default {
  extensions: [".mdx"],
  settings: {
    bullet: "-",
    listItemIndent: "one",
    incrementListMarker: false,
    emphasis: "_",
    rule: "-",
  },
  plugins: [
    // Parse frontmatter in MDX files
    "remark-frontmatter",
    // Parse MDX files
    "remark-mdx",
    // Allow HTML comments
    ["remark-comment", { "ast": true }],
    "unified-prettier",
    // Code blocks must have language specified
    "remark-lint-fenced-code-flag",
    // Headings can't increase by more than one level
    "remark-lint-heading-increment",
    // Any heading should be followed by content
    "remark-lint-no-empty-sections",
    // The first heading level should be `h2` (`h1` is `title` frontmatter)
    ["remark-lint-first-heading-level", 2],
    // Enforce `#` heading styles
    ["remark-lint-heading-style", "atx"],
  ],
};
```

Installed packages and versions:

```json
"prettier": "^3.0.3",
"remark": "^14.0.3",
"remark-cli": "^11.0.0",
"remark-comment": "^1.0.0",
"remark-frontmatter": "^5.0.0",
"remark-lint": "^9.1.2",
"remark-lint-fenced-code-flag": "^3.1.2",
"remark-lint-first-heading-level": "^3.1.2",
"remark-lint-heading-increment": "^3.1.2",
"remark-lint-heading-style": "^3.1.2",
"remark-lint-no-empty-sections": "^4.0.0",
"remark-mdx": "^2.3.0",
"remark-stringify": "^11.0.0",
"unified-prettier": "^2.0.0"
```

**Comment by remcohaszing** [comment]
The unified ecosystem is going through a bunch of small breaking changes, meaning a lot of major versions. Based on the fact that you use `remark-mdx` and `remark-lint`, you should still use `remark-cli` 11. This means you should use `unified-prettier` 1.

A new major version of `remark-mdx` will be released soon. I believe `remark-lint` and friends will follow next. Once those are related, you should update al your remark / unified related dependencies at the same time.

To get the full functionality of `remark-prettier`, you need both `unified-prettier` and [`unified-consistency`](https://github.com/remcohaszing/unified-consistency) (also version 1).

**Comment by kai687** [comment]
Thanks a lot for taking the time to explain that to me. It's really non-obvious to a newcomer like me.
