### ISSUE TITLE
Need an example

### ISSUE THREAD

**Issue by talatkuyuk** [remcohaszing/unified-prettier#3]
I need a help. 

I have a test file. I created a `compiler` and a `process` function so as to use in the tests. Here is simplified version of my code.

I couldn't figure out where to put `use(unifiedPrettier)` **for specific to that example** in order to prettify the output? I tried but got different errors.

```js
const compiler = unified()
  .use(remarkParse)
  .use(gfm)
  .use(remarkRehype, { allowDangerousHtml: true })
  .use(rehypeRaw)
  .use(rehypeStringify);

const process = async (contents: VFileCompatible): Promise<VFileCompatible> => {
  return compiler.process(contents).then((file) => file.value);
};

it("pass", async () => {
  expect(await process("Hi")).toBe("<p>Hi</p>");
});
```

**Comment by remcohaszing** [comment]
`unified-prettier` should go anywhere after the plugin that registers a compiler. So in your case, it should go after `rehype-stringify`.

Prettier options are resolved based on the file path. So you need to pass that too. Your code should become something like this:

```js
const compiler = unified()
  .use(remarkParse)
  .use(gfm)
  .use(remarkRehype, { allowDangerousHtml: true })
  .use(rehypeRaw)
  .use(rehypeStringify)
  .use(unifiedPrettier);

const process = async (contents: VFileCompatible): Promise<VFileCompatible> => {
  return compiler.process(contents).then((file) => file.value);
};

it("pass", async () => {
  expect(await process({ path: 'output.html', value: "Hi" })).toBe("<p>Hi</p>");
});
```

The intention of this plugin is to work with `unified-engine`. It could work for programmatic use, but you are probably better off passing the output to Prettier yourself. So I could make some changes to better cater this project to your needs, but I doubt it has much added value.

**Comment by remcohaszing** [comment]
I’m closing this, because there are better ways to use Prettier programmatically.
